#ifndef SRCONSTANTS_H_
#define SRCONSTANTS_H_

#include <vector>
#include <string>

#define ERROR_BUILDER_FIRST_NAME		"NULL FIRST NAME"
#define ERROR_BUILDER_LAST_NAME			"NULL LAST NAME"
#define ERROR_BUILDER_DOB				"NULL DOB"
#define ERROR_BUILDER_AGE				"NULL AGE"

#define ERROR_BUILDER_HOME_ADDRESS		"NULL HOME ADDRESS"
#define ERROR_BUILDER_EMAIL_ADDRESS		"NULL EMAIL ADDRESS"
#define ERROR_BUILDER_HOME_PHONE		"NULL HOME PHONE"
#define ERROR_BUILDER_CELL_PHONE		"NULL CELL PHONE"

#define ERROR_BUILDER_PREV_ATTENDED		"NULL PREVIOUSLY ATTENDED"
#define ERROR_BUILDER_YEARS_ATTENDED	"NULL YEARS ATTENDED"
#define ERROR_BUILDER_PREV_LOCATION		"NULL PREVIOUS LOCATION"
#define ERROR_BUILDER_ALLERGIES			"NULL ALLERGIES"

using sr_int = unsigned char;
using sr_list = std::vector<std::string>;

#endif 